"""adaugare image_url la book

Revision ID: 562e1128732b
Revises: b05e2b86679f
Create Date: 2026-07-09 14:09:00.493774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562e1128732b'
down_revision = 'b05e2b86679f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
